// @version 5.0.819
(function(r,m,k,w,L,D,E,x,y,S,o,p,M,pa,ea,u,z,A,N,T,fa,O,n){function U(a,b,d){if(!a)for(a in q)return q[a];var c=new ga(a);d&&c.xa();return q[b||a]=c}function V(a){for(var b in q)q[T](b)&&a(q[b])}function qa(a,b){return function(){a.call(b)}}function B(a,b,d,c){var f;(f=a.addEventListener)?f.call(a,b,d,p):a.attachEvent(c||"on"+b,d)}function s(a,b){return function(){a(b)}}function F(a,b,d){if(!ha)if("function"==typeof a)a();else if(ra.test(a))"string"!=typeof b&&(d=b,b=0),U(a,b,d||d===n);else if(/^_/.test(a))P[a]&&
P[a](b,d),delete P[a];else{var a=a[u]("."),c;1<a[A]&&(c=a.shift());a=a[0];if("get"==a)return sa(c,b);"set"==a?Q(c,b,d):"track"==a?W(X,c,b,d):"event"==a?W(ia,c,b,d):"cancel"==a?ta(c):"noCookies"==a?Q(c,1,p):"anonymizeIP"==a?Q(c,2,o):"tag"==a?Q(c,3,b):"load"==a?b&&b():"implode"==a&&(ha=o)}}function Q(a,b,d){var c=ja[(b+"")[N]()]||b;a?q[a].v(c,d):V(function(a){a.v(c,d)})}function sa(a,b){var d=ja[(b+"")[N]()]||b,c;if(a)return q[a].b(d);V(function(a){c=a.b(d)});return c}function ka(a,b){function d(a){return"expires="+
(new E(a)).toGMTString()+";"}var c="path=/;",f=a.b(6);f&&(c+="domain="+f+";");return{N:function(e,f){a.b(1,o)&&(k.cookie=e+"="+f+";"+d(+new E+(b?6E10:6E4))+c)},o:function(b){if(a.b(1,o))return(k.cookie.match("(^|;)\\s*"+b+"=(.*?)(;|$)")||[])[2]||M},ca:function(a){k.cookie=a+"=;"+d(0)+c}}}function W(a,b,d,c){b?a.call(q[b],d,c):V(function(b){a.call(b,d,c)})}function ta(a){W(function(){this.B()},a)}function ga(a){var b=this;b.c=a;b.Fa=p;var d=[];b.v=function(a,b){d[a]=b};b.b=function(a,b){return a in
d?d[a]:b};var c;b.xa=function(){c=x(qa(X,b),b.b(9,200))};b.B=function(){y(b.g);y(c)}}function X(a,b){function d(a){j.cb=a}var c=this,f=ua(c,a,b),e=va(c),g=wa(c,!e.I,a!==n),i=xa(),h=ya(a),v=Z(),j,k=c.b(5);y(c.g);c.k=0;c.f=p;$(c);if(!f.ga&&(!f.fa&&!(w&&"preview"==w.loadPurpose))&&(!i.d.m||!i.d.l||!(10>i.d.m&&10>i.d.l)))(c.r=v.j,c.p=v.h,j={a:c.c,cs:i.aa,cd:i.C,fl:i.ea,je:i.ha,la:i.ia,sw:i.d.m,sh:i.d.l,dm:f.da,pa:f.ma,pt:f.wa,pr:f.oa,po:f.qa,ri:e.I,ru:e.sa,ui:g.id,re:g.ta,vi:g.Aa,pv:g.ra,lv:g.ja,vw:v.V,
vh:v.T,dw:v.H,dh:v.F,st:v.j,sl:v.h,tv:"5.0",un:c.b(3),pp:g.na,cp:g.ba,ec:k,aip:c.b(2)?1:n},c.v(11,g.id),a===n&&(j.id=c.id),e.K&&(j.oe=e.K.Ca,j.ok=e.K.Ea),h&&(j.c_n=h.Y,j.c_s=h.Z,j.c_m=h.X,j.c_c=h.W,j.c_t=h.$),aa&&(t?(j.o_si=t.O,j.o_vi=t.U,j.o_ci=t.D):c.J=o),d(la(function(a){c.id=a;y(c.g);c.g=x(s(R,c),15E3);B(m,"beforeunload",s(za,c))})),ba({M:"pv",L:j}),c.id!==n)?a!==n&&(c.id=n):x(s(Aa,c),500)}function ia(a,b){if("string"==typeof b||"number"==typeof b)b={caption:b};b||(b={});b.gs_evt_name=a;R(this,
"event",b)}function R(a,b,d){if(!a.ua)if(a.id!==n){if(d===n)var c=Z(),d={vw:c.V,vh:c.T,dw:c.H,dh:c.F,st:c.j,sl:c.h,mst:a.r,msl:a.p};d=d||{};d.a=a.c;d.u=a.b(11);d.i=a.id;d.e=b;d._=D.random();d.tv="5.0";d.et=Ba(a);aa&&(a.J&&t)&&(a.J=p,d.o_si=t.O,d.o_vi=t.U,d.o_ci=t.D);d.cb=la(function(){y(a.g);if(!a.ua)a.g=x(s(R,a),17500+D.random()*5E3)});ba({M:"ping",L:d})}else{var f=arguments;x(function(){R.apply({},f)},5E3)}}function ma(){var a=m.olark;a&&a("api.boot.onIdentityReady",function(a,d,c){t={O:a,U:d,D:c}});
aa=!!a}function ba(a){function b(a){var b=[],c;for(c in a)a[T](c)&&a[c]!==n&&b.push((S||escape)(c)+"="+(S||escape)(a[c]));return b.join("&")}function d(){e&&f.removeChild(e);e=M;ca=(ca+1)%c[A];ba(a)}a.Q===n&&(a.Q=5);if(--a.Q){var c=["data.gosquared.com/"],f=k[fa]("head")[0],e=k[ea]("script"),g=p,i=x(d,1E4),h=a.M+"?"+b(a.L);e.src=("https:"==G().A?"https":"http")+"://"+c[ca]+h;e.onload=e.onreadystatechange=function(b){b=this.readyState;if(!g&&(!b||b=="loaded"||b=="complete")){g=o;a.va&&a.va();e&&f.removeChild(e);
e=M;y(i)}};f.appendChild(e)}}function la(a){var b="_"+Ca++;P[b]=a;return b}function H(a){function b(){var a=f.name;a&&(f.name=a[u](d)[0])}var d=":_GS_:",c;if(H.P)return H.P;var f=m.top;H.P=c={G:function(){b();f.name=(f.name||"")+d+[a,c.uid,c.s]}};try{var e=f.name||"";if(-1!=e[O](d)){var g=e[u](d)[1][u](",");g[0]==a&&(c.uid=g[1]||"",c.s=g[2]||"")}b()}catch(i){c.G=function(){}}return c}function ua(a,b,d){b=G(G(b).w);return{ma:b.za+(a.b(7,o)?b.S:"")[z](/[?&](utm_[^=]*|gclid)=[^&]*/g,"")[z](/^&/,"?")+
(a.b(8)?b.ya:""),wa:d!==n?d:k.title,da:b.R,oa:b.A,qa:b.z||"-",ga:"file:"==b.A,fa:/fb_xd_(bust|fragment)/.test(b.w)}}function ya(a){var a=G(a).S,b,d,c,f;b=/[?&]([^=]+)=([^&]*)/g;d={};for(f=decodeURIComponent;c=b.exec(a[z](/\+/g," "));d[f(c[1])]=f(c[2]));var e;if(a&&(e=d.utm_campaign))return{Y:e,Z:d.utm_source,X:d.utm_medium,$:d.utm_term,W:d.utm_content}}function xa(){var a={d:{m:0,l:0},C:"-",ia:(w.language||w.browserLanguage||"-")[N](),ha:+w.javaEnabled(),aa:k.characterSet||k.charSet||"-",ea:function(a,
d){var c,f,e,g,i;if(w&&(c=w.plugins)&&0<(f=c[A]))for(i=0;i<f;i++){if(-1<(g=c[i]).name[O](e=a+" "+d))return c=g.description[u](e+" "),c[1]}else if(c=m.ActiveXObject){try{if(g=(new c((e=a+d+".")+a+d)).GetVariable("$version"))return g=g[u](" ")[1][u](","),g[0]+"."+g[1]+" r"+g[2]}catch(h){}for(i=13;--i;)try{if(g=new c(e+e+i),self.Da=g&&g.Ba,g)return i+".0"}catch(k){}}return"-"}("Shockwave","Flash")};L&&(a.d={m:L.width,l:L.height},a.C=L.colorDepth);return a}function Z(){function a(a){return m["inner"+
a]||c&&c[f="client"+a]||d&&d[f]}function b(a){return D.max(d[f="scroll"+a],c[f],d[f="offset"+a],c[f],d[f="client"+a],c[f])}var d=k.body,c=k.documentElement,f;return{V:a("Width"),T:a("Height"),H:b("Width"),F:b("Height"),h:m.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft||0,j:m.pageYOffset||d&&d.scrollTop||c&&c.scrollTop||0}}function $(a){y(a.ka);a.ka=x(s(na,a),15E3);a.f||(a.f=o,a.n=+new E)}function na(a){a.f&&(a.f=p,a.k=(a.k||0)+ +new E-a.n)}function Ba(a){var b=a.k,d=+new E;a.f&&(b+=d-a.n,a.n=d);a.k=
0;return b}function Da(a){$(a);var b=Z();b.j>a.r&&(a.r=b.j);b.h>a.p&&(a.p=b.h)}function Aa(a){var b=s($,a);B(k,"mousemove",b);B(k,"keydown",b);B(m,"scroll",s(Da,a));B(k,"focus",b,"focusin");B(k,"blur",s(na,a),"focusout")}function va(a){var a=a.b(10,k.referrer),b=k.domain,d=p;!a||/^(chrome|about|file):$/.test(a)?a="-":(b=G(a).R[O](b),d=0<=b&&8>=b,a=/^\[.*\]$/.test(a)?"-":a);return{I:+d,sa:a}}function za(a){var b=ka(a);a.b(1)?b.N("gs_p_"+a.c,a.id):(b=H(a.c),b.s=a.id,b.G())}function wa(a,b,d){var c=
ka(a,1),f=H(a.c),e=c.o("gs_u_"+a.c)||c.o("gs_u")||f.uid,g=1,i=1,h=(e||"")[u](":"),k,j=o,l=0,Y;!e||!e.match(/^[0-9\:]*$/)?(j=p,e=0|D.random()*pa):(e=h[0],2>h[A]&&(h[1]=2019,h[2]=4621),4>h[A]&&(h[3]=0),g=(h[1]-2019)/548+ +!!b,i=(h[2]-4621)/379+1,l=h[3]/1E3);c.N("gs_u_"+a.c,f.uid=[e,2019+548*g,4621+379*i,+new E].join(":"));b=c.o("gs_p_"+a.c)||f.s;b!==M&&b!==n&&(Y=b,c.ca("gs_p_"+a.c));d&&(Y=a.id);if((a=a.b(4))&&"object"==typeof a){k=[];for(var m in a)a[T](m)&&k.push(m+"="+("gravatar"==m?Ea(a[m][z](/^\s+|\s+$/g,
"")[N]()):a[m]));k=k.join("|")}return{id:+e,Aa:g,ra:i,ja:~~l,ta:j,na:Y,ba:k}}var I,C=m._gs||(I=o,function(){C.q.push(arguments)});C.q=C.q||[];if(!C.t){var ra=/^GSN-.*-.$/,q={};if(r){var l,J;for(l in r)J=r[l],"acct"==l?(U(J,"default",o),C("load",function(){function a(a){b[a.shift()].apply(b,a)}var b=r.DefaultTracker=q["default"],d={push:a};if(l=r.q)for(;J=l.shift();)a(J);r.q=d;(l=r.load)&&l(b)})):"load"!=l&&"q"!=l&&C("set",l,J);l=ga.prototype;l.TrackView=X;l.TrackEvent=ia;l.Cancel=function(){this.B()};
r.Tracker=U;r.Cancel=s(F,"cancel")}var ha,ja={usecookies:1,anonymiseip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,trackdelay:9,referrer:10,visitorid:11},Ea=function(a){function b(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&1)}for(var d=[],c=0;64>c;)d[c]=0|4294967296*D.abs(D.sin(++c));return function(c){for(var e,g,i,h,k=[],c=unescape(S(c)),j=c[A],m=[e=1732584193,g=-271733879,~e,~g],l=0;l<=j;)k[l>>2]|=(c.charCodeAt(l)||128)<<8*(l++%4);k[c=(j+8>>6)*a+14]=8*j;for(l=0;l<
c;l+=a){j=m;for(h=0;64>h;)j=[i=j[3],b(e=j[1],(i=b(b(j[0],[e&(g=j[2])|~e&i,i&e|~i&g,e^g^i,g^(e|~i)][j=h>>4]),b(d[h],k[[h,5*h+1,3*h+5,7*h][j]%a+l])))<<(j=[7,12,17,22,5,9,14,20,4,11,a,23,6,10,15,21][4*j+h++%4])|i>>>32-j),e,g];for(h=4;h;)m[--h]=b(m[h],j[h])}for(c="";32>h;)c+=(m[h>>3]>>4*(1^h++&7)&15).toString(a);return c}}(16),aa=p,t,ca=0,P={},Ca=0,G=function(a){return function(b,d){b===n&&(b=location.href);a.href=b;d={za:a.pathname[z](/^([^\/]|$)/,"/$1"),ya:a.hash[z](/^#$/,""),A:a.protocol[z](/^:$/,
"")||location.protocol,R:a.hostname||location.hostname,w:a.href,S:a.search,z:a.port};-1==d.w[O](":"+d.z)&&(d.z="");return d}}(k[ea]("a")),da=C.q;m._gs=F;F.t="5.0";for(var K;K=da.shift();)F.apply({},K);if(I){I=k[fa]("script");da=I[A];K=0;for(var oa;K<da;)if(oa=I[K++].getAttribute("data-gs")){F(oa);break}}ma();B(m,"load",ma)}})(window.GoSquared,window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,1,0,null,2147483647,"createElement","split","replace","length","toLowerCase",
"hasOwnProperty","getElementsByTagName","indexOf");
